version: '3.9'
services:
    api-service:
        build: ./app/
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8080:8080
        environment:
            PORT: 8080
            FLASK_DEBUG: 1